conda-forge/cds-crtools-feedstock

.ci_support/linux_64_root_base6.26.0.yaml
.ci_support/linux_64_root_base6.26.2.yaml
.ci_support/migrations/python310.yaml
recipe/meta.yaml

This PR fixes the python pins that were supposed to be fixed by #10.
Checklist

Fix python pins

---

.ci_support/linux_64_.yaml
.circleci/config.yml
.github/workflows/automerge.yml
.scripts/build_steps.sh
README.md
recipe/meta.yaml

This PR removes any and all references to `openssl` in the recipe, I think these were here originally to help the solver through the start of the openssl migration.
Checklist

Remove placeholder openssl pins

---

.ci_support/migrations/root_base6266.yaml
.ci_support/migrations/root_base6268.yaml
recipe/meta.yaml

Rebuild for gds 3.0.0

---

.azure-pipelines/azure-pipelines-osx.yml
.ci_support/osx_arm64_.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
conda-forge.yml
recipe/meta.yaml

Checklist
* [ x] Bumped the build number (if the version is unchanged)
* [x ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
Try to build for osx-arm

trying to get this to build for osx-arm

---

.ci_support/linux_64_.yaml
recipe/meta.yaml

Rebuild for root_base6280

---

recipe/meta.yaml

Checklist
* [x ] Bumped the build number (if the version is unchanged)

Fix URL to point at new location of repository.

---

recipe/meta.yaml

Improves python package installation.
Checklist
* [x ] Ensured the license file is being packaged.

Version bumped to 3.1.5.dev4

---

recipe/meta.yaml

Checklist
* [x ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
Removes pybind and gds-gui dependencies, since these are now in-tree.

3.1.5.dev5

---

recipe/meta.yaml

Checklist
* [ x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
fix an empty return on a function

Bump version to 3.1.5.dev6

---

recipe/meta.yaml

Checklist
* [ x] Bumped the build number (if the version is unchanged)
* [ x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

3.1.5.dev9

---

recipe/meta.yaml

Checklist
* [x ] Ensured the license file is being packaged.

Bump to version 3.1.5.dev9

---

recipe/meta.yaml

Checklist
* [ x] Bumped the build number (if the version is unchanged)

Bump to version 3.1.5.dev11

---

recipe/meta.yaml

Release version 3.1.5.dev12

---

recipe/meta.yaml

Checklist
* [x ] Ensured the license file is being packaged.

Bump to version 3.1.5_dev13

---

recipe/meta.yaml

Release 4.0.0

---

recipe/meta.yaml

4.0.1 release

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/meta.yaml

Checklist
* [ x] Bumped the build number (if the version is unchanged)

Build for both root 6.26 and 6.28

---

recipe/meta.yaml

This change seems to be necessary to differentiate all packages on root_base.
Checklist

Explicitly add root_base into packages that ulitmately depend on it.

---

recipe/meta.yaml

Checklist
* [x ] Ensured the license file is being packaged.

Bump to version 4.0.2

---

.ci_support/linux_64_python3.10.____cpython.yaml
.ci_support/linux_64_python3.11.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/osx_64_python3.10.____cpython.yaml
.ci_support/osx_64_python3.11.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.ci_support/osx_arm64_python3.10.____cpython.yaml
.ci_support/osx_arm64_python3.11.____cpython.yaml
.ci_support/osx_arm64_python3.8.____cpython.yaml
.ci_support/osx_arm64_python3.9.____cpython.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

For integration with the rest of conda-forge, in particular the IGWN Conda Distribution, we really need to follow the `root_base` pin from conda-forge.
Checklist

Fix ROOT pins.

---

recipe/meta.yaml

Checklist
* [ x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Reset build number back to zero

---

recipe/meta.yaml

Bump version to 4.0.4

---

recipe/meta.yaml

Bump to version 4.1.2

---

recipe/meta.yaml

Bump branch to 4.1.3

---

.azure-pipelines/azure-pipelines-osx.yml
recipe/conda_build_config.yaml
recipe/meta.yaml

Bump version to 4.1.4

---

recipe/meta.yaml

Fix license attribute
